source "https://rubygems.org"

gemspec
gem 'angularjs-rails', '~> 1.2.16'
gem 'bootstrap-sass'
# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
