source "https://rubygems.org"

gemspec

gem 'rails', '4.1.1'
gem 'pg', '~> 0.17.1'
gem 'oj'
gem 'devise', '~> 3.2.4'

gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'angularjs-rails', '~> 1.2.16'
gem 'font-awesome-rails', '~> 4.1.0.0'
gem 'codemirror-rails', '~> 4.2'

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
